/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.fernandowirtz.relojdigital.Alarma;
import com.fernandowirtz.relojdigital.ModeloReloj;
import controlador.ControladorReloj;
import java.awt.Color;
import java.util.prefs.Preferences;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author hector.garaboacasas
 */
public class RelojPane extends javax.swing.JPanel {

    /**
     * Creates new form RelojPane
     */
    ModeloReloj modelo;

    public RelojPane() {
        initComponents();

       

        modelo = new ModeloReloj();

        new ControladorReloj(modelo, this);
        
        jLabel1.setFont(modelo.getFuente());
        jLabel2.setFont(modelo.getFuente());
        jLabel3.setFont(modelo.getFuente());
        jLabel4.setFont(modelo.getFuente());

        if(modelo.isFechaVisible()){
            tbtnFecha.setBackground(Color.green);
            tbtnFecha.setSelected(false);
        }else{
            tbtnFecha.setBackground(Color.red);
            tbtnFecha.setSelected(true);
        }
        if(modelo.isFormato24h()){
            tbtnFormato.setBackground(Color.green);
            tbtnFormato.setSelected(false);
        }else{
            tbtnFormato.setBackground(Color.red);
            tbtnFormato.setSelected(true);
        }
        

        
  
        
        //añadir fuente 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaAlarma = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnAñadirAlarma = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        diaLista = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLAlarmas = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarAlarma = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        tbtnFecha = new javax.swing.JToggleButton();
        tbtnFormato = new javax.swing.JToggleButton();
        btnDialogAlarma = new javax.swing.JButton();
        btnDialogLista = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Fecha");

        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Hora");

        txtMensaje.setBackground(new java.awt.Color(153, 153, 153));
        txtMensaje.setColumns(20);
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));
        txtMensaje.setRows(5);
        txtMensaje.setName(""); // NOI18N
        jScrollPane1.setViewportView(txtMensaje);

        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Mensaje");

        txtFecha.setBackground(new java.awt.Color(153, 153, 153));
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setText("yyyy/MM/dd");
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        btnAñadirAlarma.setBackground(new java.awt.Color(153, 153, 153));
        btnAñadirAlarma.setForeground(new java.awt.Color(0, 0, 0));
        btnAñadirAlarma.setText("Añadir alarma");
        btnAñadirAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirAlarmaActionPerformed(evt);
            }
        });

        txtHora.setBackground(new java.awt.Color(153, 153, 153));
        txtHora.setForeground(new java.awt.Color(0, 0, 0));
        txtHora.setText("HH:mm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(btnAñadirAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(1, 1, 1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(btnAñadirAlarma)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout diaAlarmaLayout = new javax.swing.GroupLayout(diaAlarma.getContentPane());
        diaAlarma.getContentPane().setLayout(diaAlarmaLayout);
        diaAlarmaLayout.setHorizontalGroup(
            diaAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diaAlarmaLayout.setVerticalGroup(
            diaAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLAlarmas.setBackground(new java.awt.Color(153, 153, 153));
        jLAlarmas.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jLAlarmas);

        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Lista de Alarmas");

        btnEliminarAlarma.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarAlarma.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarAlarma.setText("Eliminar Alarma");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEliminarAlarma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnEliminarAlarma)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout diaListaLayout = new javax.swing.GroupLayout(diaLista.getContentPane());
        diaLista.getContentPane().setLayout(diaListaLayout);
        diaListaLayout.setHorizontalGroup(
            diaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diaListaLayout.setVerticalGroup(
            diaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(new java.awt.Color(0, 255, 0));
        setToolTipText("");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 204, 0));

        lblHora.setBackground(new java.awt.Color(0, 0, 0));
        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 255, 0));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tbtnFecha.setText("Mostrar Fecha");

        tbtnFormato.setText("Formato 24/12h");

        btnDialogAlarma.setText("Crear alarma");
        btnDialogAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogAlarmaActionPerformed(evt);
            }
        });

        btnDialogLista.setText("Lista Alarmas");
        btnDialogLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tbtnFecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbtnFormato)))))
                            .addGap(25, 25, 25))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnDialogAlarma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDialogLista)
                        .addGap(36, 36, 36)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnFormato)
                    .addComponent(tbtnFecha))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDialogLista)
                    .addComponent(btnDialogAlarma))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirAlarmaActionPerformed

    }//GEN-LAST:event_btnAñadirAlarmaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnDialogAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogAlarmaActionPerformed

    }//GEN-LAST:event_btnDialogAlarmaActionPerformed

    private void btnDialogListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogListaActionPerformed

    }//GEN-LAST:event_btnDialogListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirAlarma;
    private javax.swing.JButton btnDialogAlarma;
    private javax.swing.JButton btnDialogLista;
    private javax.swing.JButton btnEliminarAlarma;
    private javax.swing.JDialog diaAlarma;
    private javax.swing.JDialog diaLista;
    private javax.swing.JList<Alarma> jLAlarmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JToggleButton tbtnFecha;
    private javax.swing.JToggleButton tbtnFormato;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables

    public void actualizarHora(String hora) {
        lblHora.setFont(modelo.getFuente2());
        lblHora.setText(hora);

    }

    public void actualizarFecha(String fecha) {
        lblFecha.setFont(modelo.getFuente());
        lblFecha.setText(fecha);

    }

    public JToggleButton getTbtnFecha() {
        tbtnFecha.setFont(modelo.getFuente());
        return tbtnFecha;
    }

    public JToggleButton getTbtnFormato() {
        tbtnFormato.setFont(modelo.getFuente());
        return tbtnFormato;
    }

    public JButton getBtnAñadirAlarma() {
        btnAñadirAlarma.setFont(modelo.getFuente());
        return btnAñadirAlarma;
    }

    public JTextField getTxtFecha() {
        txtFecha.setFont(modelo.getFuente());
        return txtFecha;
    }

    public JTextField getTxtHora() {
        txtHora.setFont(modelo.getFuente());
        return txtHora;
    }

    public JTextArea getTxtMensaje() {
txtMensaje.setFont(modelo.getFuente());
        return txtMensaje;
    }

    public JList<Alarma> getjLAlarmas() {
        jLAlarmas.setFont(modelo.getFuente());
        return jLAlarmas;
    }

    public JButton getBtnEliminarAlarma() {
        btnEliminarAlarma.setFont(modelo.getFuente());
        return btnEliminarAlarma;
    }

    public JButton getBtnDialogAlarma() {
        btnDialogAlarma.setFont(modelo.getFuente());
        
        return btnDialogAlarma;
    }

    public JButton getBtnDialogLista() {
        btnDialogLista.setFont(modelo.getFuente());
        return btnDialogLista;
    }

    public JDialog getDiaAlarma() {
        
        return diaAlarma;
    }

    public JDialog getDiaLista() {
        return diaLista;
    }

}
